clc
clear all
close all
set(0,'defaultfigurecolor',[1 1 1]);% set figure background color
addpath(genpath('/Users/guofanhua/Desktop/gfh/tools/MatlabTools/BrainSpace-latest/matlab'))

%% ======================= step 1 for disposal all data

%% input data
step01_CBFandCCSImaps_00_init;
step01_CBFandCCSImaps_00_ComputeBasicResults;


%% CBF PC2/3
[tmp, explained] = subfun_PCAtoPC(zscore(Data_Val_bil));
CBF_ValPC1_bil = tmp(:,1);
CBF_ValPC2_bil = tmp(:,2);
CBF_ValPC3_bil = tmp(:,3);


[tmp, explained_uni] = subfun_PCAtoPC(zscore(Data_Val_uni));
CBF_ValPC1_uni = tmp(:,1);
CBF_ValPC2_uni = tmp(:,2);
CBF_ValPC3_uni = tmp(:,3);

%% lobe map
tmp = atlas_info.Lobe;
atlas_lobeindex = zeros(size(tmp));
for i = 1:numel(atlas_lobeindex)
    switch tmp{i}
        case 'Fr'
            atlas_lobeindex(i) = 1;
        case 'Ins'
            atlas_lobeindex(i) = 2;
        case 'Occ'
            atlas_lobeindex(i) = 3;
        case 'Par'
            atlas_lobeindex(i) = 4;
        case 'Temp'
            atlas_lobeindex(i) = 5;
    end
end
atlas_lobeindex(181:end) = atlas_lobeindex(1:180);

%% check atlas label
check = [atlas_info.regionLongName(1:180) atlas_info.regionLongName(181:360) atlas_info.Lobe(1:180) atlas_info.Lobe(181:360)];


%% batch write to 1D for compute spin-null by neuromaps
% bil
OutNames = {'CBF_Mean_PScs', 'CBF_PC1_Val',...
            'CBF_PC2_Val','CBF_PC3_Val',...
            'CBF_PC1_Val_Layer1',...
            'CBF_PC1_Val_Layer2',...
            'CBF_PC1_Val_Layer3',...
            'CBF_PC1_Val_Layer4',...
            'CBF_PC1_Val_Layer5',...
            'CBF_PC1_Val_Layer6'};  % there layers 1-6 actually are L6-L1
OutDatas = {CBF_meanPScs_bil, CBF_ValPC1_bil,...
            CBF_ValPC2_bil, CBF_ValPC3_bil,...
            CBF_ValPC1_Layer_bil{1},...
            CBF_ValPC1_Layer_bil{2},...
            CBF_ValPC1_Layer_bil{3},...
            CBF_ValPC1_Layer_bil{4},...
            CBF_ValPC1_Layer_bil{5},...
            CBF_ValPC1_Layer_bil{6},...
            CBFsnr_mean_bil, CNRcm_g};
UniOrBil = 2;  % 1:uni  2:bil
for i = 1:numel(OutNames)
    if UniOrBil == 1
        OutData = [OutDatas{i}; OutDatas{i}];
        suffix = '_uni.1D';
    else
        OutData = OutDatas{i};
        suffix = '_bil.1D';
    end
    % do it
    OutDir = '../Data/group';
    save([OutDir '/' OutNames{i} suffix],'OutData','-ascii');
end


% uni
OutNames = {'CBF_Mean_PScs', 'CBF_PC1_Val',...
            'CBF_PC2_Val','CBF_PC3_Val',...
            'CBF_PC1_Val_Layer1',...
            'CBF_PC1_Val_Layer2',...
            'CBF_PC1_Val_Layer3',...
            'CBF_PC1_Val_Layer4',...
            'CBF_PC1_Val_Layer5',...
            'CBF_PC1_Val_Layer6'};  % there layers 1-6 actually are L6-L1
OutDatas = {CBF_meanPScs_uni, CBF_ValPC1_uni,...
            CBF_ValPC2_uni, CBF_ValPC3_uni,...
            CBF_ValPC1_Layer_uni{1},...
            CBF_ValPC1_Layer_uni{2},...
            CBF_ValPC1_Layer_uni{3},...
            CBF_ValPC1_Layer_uni{4},...
            CBF_ValPC1_Layer_uni{5},...
            CBF_ValPC1_Layer_uni{6}};
UniOrBil = 1;  % 1:uni  2:bil
for i = 1:numel(OutNames)
    if UniOrBil == 1
        OutData = [OutDatas{i}; OutDatas{i}];
        suffix = '_uni.1D';
    else
        OutData = OutDatas{i};
        suffix = '_bil.1D';
    end
    % do it
    OutDir = '../Data/group';
    save([OutDir '/' OutNames{i} suffix],'OutData','-ascii');
end


%% write to map plot by R
OutNames = {'CBF_Mean_PScs_bil.csv', 'CBF_PC1_Val_bil.csv',...
            'Mito_CI_bil.csv', 'Mito_CII_bil.csv',...
            'Mito_CIV_bil.csv', 'Mito_MitoD_bil.csv',...
            'BB_G1_bil.csv', 'CBF_PC1_Val_L6_bil.csv',...
            'CBF_PC1_Val_L5_bil.csv', 'CBF_PC1_Val_L4_bil.csv',...
            'CBF_PC1_Val_L3_bil.csv', 'CBF_PC1_Val_L2_bil.csv',...
            'CBF_PC1_Val_L1_bil.csv', 'intersubjvar.csv',...
            'myelinmap.csv', 'thickness.csv',...
            'Economo-Koskinas-cytoarchitectonics.csv', 'StructualConnection_G1.csv',...
            'Yeo2011-FunctionNetwork.csv', 'CNR_G1.csv',...
            'SNRmean.csv', 'FunctionGradient1.csv',...
            'lobe.csv', 'CBF_PC2_Val_bil.csv',...
            'CBF_PC3_Val_bil.csv'};
OutDatas = {CBF_meanPScs_bil, CBF_ValPC1_bil,...
            zMitoData(:,1), zMitoData(:,2),...
            zMitoData(:,3), zMitoData(:,4),...
            BB_gradient, CBF_ValPC1_Layer_bil{1},...
            CBF_ValPC1_Layer_bil{2}, CBF_ValPC1_Layer_bil{3},...
            CBF_ValPC1_Layer_bil{4}, CBF_ValPC1_Layer_bil{5},...
            CBF_ValPC1_Layer_bil{6}, all_other_maps.maps{48},...
            all_other_maps.maps{26}, all_other_maps.maps{27},...
            EKc, scm_g(:,1),...
            Yeo_FN, CNRcm_g(:,1),...
            CBFsnr_mean_bil, all_other_maps.maps{38},...
            atlas_lobeindex, CBF_ValPC2_bil,...
            CBF_ValPC3_bil};
Datalabel = [1:360]';

for i = 1:numel(OutNames)
    tmp = subfun_write_to_MapPlot_byR(OutDatas{i},Datalabel,atlas_info,[Group_dir OutNames{i}]);
end



